---
- name: GRAB F5 FACTS
  hosts: F5-Device-Inventory
  gather_facts: false

  tasks:
  - name: COLLECT BIG_IP FACTS
      f5networks.f5_modules.bigip_device_info:
        gather_subset:
          - system-info
        provider:
          server: "{{private_ip}}"
          user: "{{ansible_user}}"
          password: "{{ansible_password}}"
          server_port: 8443
          validate_certs: false
      register: device_facts

    
